global:
    exporters:
        e1: # give a name you like, will not be used
            format: "text"
            to: "stdout"
        e2:
            format: "json"
            to: "file://tmp/perf-99.json"
    num_threads_building: 16
    num_threads_searching: 16

99/DEEP1B:
    datapath: "/tmp/data/deep-image-96-angular.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":96,"dtype":"float32","metric_type":"cosine","index_param":{"base_quantization_type":"fp32","max_degree":96,"ef_construction":400, "precise_quantization_type":"fp32", "use_reorder":true}}'
    search_params: '{"hgraph":{"ef_search":150}}'
    index_path: "/tmp/deep-image-96-angular/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: false

99/GIST:
    datapath: "/tmp/data/gist-960-euclidean.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":960,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"sq8_uniform","max_degree":96,"ef_construction":400, "precise_quantization_type":"fp32", "use_reorder":true}}'
    search_params: '{"hgraph":{"ef_search":400}}'
    index_path: "/tmp/gist-960-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: false

99/SIFT:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"sq8_uniform","max_degree":32,"ef_construction":400, "precise_quantization_type":"fp32", "use_reorder":true}}'
    search_params: '{"hgraph":{"ef_search":99}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: false

99/GloVe-100:
    datapath: "/tmp/data/glove-100-angular.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":100,"dtype":"float32","metric_type":"cosine","index_param":{"base_quantization_type":"sq8_uniform","max_degree":96,"ef_construction":600, "precise_quantization_type":"fp32", "use_reorder":true}}'
    search_params: '{"hgraph":{"ef_search":600}}'
    index_path: "/tmp/glove-100-angular/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: false

99/NYTimes:
    datapath: "/tmp/data/nytimes-256-angular.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":256,"dtype":"float32","metric_type":"cosine","index_param":{"base_quantization_type":"sq8_uniform","max_degree":96,"ef_construction":600, "precise_quantization_type":"fp32", "use_reorder":true}}'
    search_params: '{"hgraph":{"ef_search":600}}'
    index_path: "/tmp/nytimes-256-angular/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: false

99/OPENAI:
    datapath: "/tmp/data/openai-1536-500k-angular.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":1536,"dtype":"float32","metric_type":"cosine","index_param":{"base_quantization_type":"fp32","max_degree":96,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":74}}'
    index_path: "/tmp/openai-1536-500k-angular/index/hgraph_index"
    topk: 10
    search_mode: "knn"
    delete_index_after_search: false

99/COHERE:
    datapath: "/tmp/data/cohere-768-1m-angular.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":768,"dtype":"float32","metric_type":"cosine","index_param":{"base_quantization_type":"sq8_uniform","max_degree":64,"ef_construction":400, "precise_quantization_type":"fp32", "use_reorder":true}}'
    search_params: '{"hgraph":{"ef_search":185}}'
    index_path: "/tmp/cohere-768-1m-angular/index/hgraph_index"
    topk: 10
    search_mode: "knn"
    delete_index_after_search: false
