import os
from setuptools import setup, Extension

def _read_version():
    # The _version.py file is generated by scripts/python/prepare_python_build.sh
    # We read it here to set the version statically.
    here = os.path.dirname(os.path.abspath(__file__))
    _version_file = os.path.join(here, 'pyvsag', '_version.py')
    
    if os.path.exists(_version_file):
        ns = {}
        with open(_version_file) as f:
            exec(f.read(), ns)
        return ns.get('__version__')
    return '0.0.0'

# All other configuration is in setup.cfg / pyproject.toml.
# This file is kept for the C-extension definition.
setup(
    version=_read_version(),
    ext_modules=[Extension('example', sources=['example.c'])],
    zip_safe=False,
)
